os:
  - osx
  - linux

sudo: required

language: go

go: 1.5.1

addons:
  apt:
    sources:
      - deadsnakes
      - ubuntu-sdk-team
    packages:
      - libonig-dev
      - python3.5
      - python3.5-dev
      - qtdeclarative5-private-dev

install:
  - ./tasks/general/ci/install.sh
  - ./tasks/local/ci/install.sh

script:
  - ./tasks/general/ci/run_tests.sh main
  - ./tasks/local/ci/build.sh
  - ./tasks/general/ci/check_fmt.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3e692a5224c8490f19bd
    on_success: change
    on_failure: always
    on_start: false
